parameters:
#    neralind_main.example.class: Neralind\MainBundle\Example

services:
#    neralind_main.example:
#        class: %neralind_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
