tag:
    pattern:  /
    defaults: { _controller: "NeralindTagBundle:Tag:index" }

tag_show:
    pattern:  /{id}/show
    defaults: { _controller: "NeralindTagBundle:Tag:show" }

tag_new:
    pattern:  /new
    defaults: { _controller: "NeralindTagBundle:Tag:new" }

tag_create:
    pattern:  /create
    defaults: { _controller: "NeralindTagBundle:Tag:create" }
    requirements: { _method: post }

tag_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "NeralindTagBundle:Tag:edit" }

tag_update:
    pattern:  /{id}/update
    defaults: { _controller: "NeralindTagBundle:Tag:update" }
    requirements: { _method: post|put }

tag_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "NeralindTagBundle:Tag:delete" }
    requirements: { _method: post|delete }
