neralind_resource:
    resource: "@NeralindResourceBundle/Resources/config/routing.yml"
    prefix:   /

neralind_tag:
    resource: "@NeralindTagBundle/Resources/config/routing.yml"
    prefix:   /

neralind_user:
    resource: "@NeralindUserBundle/Resources/config/routing.yml"
    prefix:   /

